### ISSUE TITLE
Idea: have a single user-local install of the actual binary

### ISSUE THREAD

**Issue by fearthecowboy** [cspotcode/npm-get-powershell#10]
`get-powershell` is really similar in nature to the `dotnet-2.1` and `dotnet-2.0.0` packages that I built. The difference is that I installed the actual platform specific binary in `$home/.net\....` so that multiple installs would not have to have a separate copy of the binary.

Might be an idea to not install the binary relative to the installed npm package, but scope it to a common location.

**Comment by fearthecowboy** [comment]
Oh. It *does*

my bad.

**Comment by cspotcode** [comment]
Yes!  Great minds think alike.  Good to know about those dotnet packages; I'm getting into C# a bit more so I might be using them soon.

**Comment by fearthecowboy** [comment]
Yeah, I needed a decent, cross platform install that didn't require elevation/root. 

Took a bit of tweaking to build the dependent packages just right, but they seem to work pretty nicely.
