### ISSUE TITLE
If an instance of pwsh is open in another window, installation fails [Windows]

### ISSUE THREAD

**Issue by fearthecowboy** [cspotcode/npm-get-powershell#11]
Installed `get-powershell` in a local folder, and then ran it.

In another window, tried to install it in another folder, and got:

![image](https://user-images.githubusercontent.com/133736/45901974-c2c2ea80-bd99-11e8-80cf-67b183f0c254.png)

**Comment by cspotcode** [comment]
That's troubling; it shouldn't be doing any extraction for the second installation.  It should just set up the appropriate symlink / shim script.  Maybe there's a logic mistake.

**Comment by fearthecowboy** [comment]
The assert is failing with the mode check. I sent a PR to correct it on windows

**Comment by fearthecowboy** [comment]
Confirmed, this is fixed with #12
