### ISSUE TITLE
Document PowerShell dependencies

### ISSUE THREAD

**Issue by cspotcode** [cspotcode/npm-get-powershell#8]
I had to install libunwind8 on Ubuntu before pwsh would run.

I don't think get-powershell should be invoking `sudo apt install` but I can add a list of dependencies to the README.

Does this affect Mac at all?  I assume the Mac builds are compiled against only components bundled with MacOS.

**Comment by fearthecowboy** [comment]
Had similar problems with the `dotnet-` packages. It works ok on desktop variants, but on server variants, the dependencies are not all installed. 

Had a really interesting discussion with the .NET folks about their definition of 'no dependencies needed' . 

On MacOS, I think they finally static linked their dependency for SSL, which should mean that you're good  there.

**Comment by cspotcode** [comment]
Thanks, good to know.  I think if I ever address this issue, I'll just attempt to run `pwsh -nologo -noprofile -command {}` and if it fails, show a log message that says something like "pwsh failed to start.  You probably need to install libunwind8."

**Comment by cspotcode** [comment]
I referenced this issue in the latest README.  Hopefully if people hit issues they can comment about their experiences here.  Closing this since I don't think I'll be writing a comprehensive list of dependencies.
